### ISSUE TITLE
Self-hosted - Federation: Publishing schemas failed - missing initial type Query

### ISSUE THREAD

**Issue by Huljo** [kamilkisiela/graphql-hive#903] opened 2022-12-27 13:09 UTC
I'm currently trying to publish a federated schema in last version of Hive self-hosted ([docker-compose.community.yml](https://github.com/kamilkisiela/graphql-hive/blob/main/docker-compose.community.yml) & [065a699ce8324c36525b95ece37f870935d86efd](https://github.com/kamilkisiela/graphql-hive/commit/065a699ce8324c36525b95ece37f870935d86efd) ). 

I've created a Federated project with basic stages, while running command `hive schema:publish --registry=http://localhost:8082/graphql --service serviceone --url http://service1.local/ --author MyAuthorName --commit 0000 service1.graphql` I got an error mentioning missing types `Query`: 
```` 
- [serviceone] Query -> `Query` is an extension type, but `Query` is not defined in any service
````

`service1.graphql` : 
````graphql
extend type Query {
  getContent(id: String!): String
}
````

**Comment by dotansimha** [comment] 2022-12-27 13:14
Hi @Huljo , does your initial schema actually needs `extend` keyword? I'm pretty sure Federation merger should be able to merge the root `Query` type as-is, without `extend`.

**Comment by Huljo** [comment] 2022-12-27 13:19
Hi @dotansimha 
Not sure but this is how I send it to Apollo Studio with only `extend Query` in my services, no `type Query`. 
I can turn it as a declaration instead of extend but just want to be compatible with both platforms. Im using Federation 1 btw.

**Comment by Huljo** [comment] 2022-12-27 15:47
I just realized that this error is not due to missing Query type but missing Product type (I've also added an extend on a type Product - not published by Product service yet) : 

Error while publishing schema with `extend Query` + `extend Product` will throw an error about missing Query & missing Product type: 
`Schema`
````graphql
extend type Query {
  getContent(id: String!): String
}

extend type Product @key(fields: "reference") {
  reference: String @external
}

type BundleNode {
  children: [BundleChildrenItem]
}

union BundleChildrenItem = Product | BundleNode
````
`error` :
````
✖ Detected 4 errors

   - Unknown type Product.
   - [serviceone] Query -> `Query` is an extension type, but `Query` is not defined in any service
   - [serviceone] Product -> `Product` is an extension type, but `Product` is not defined in any service
   - Query root type must be provided.

✖ Failed to publish schema
```` 

After deleting any reference of unpublished type `Product` I got no more error about Query type: 
`schema`:
````graphql
extend type Query {
  getContent(id: String!): String
}

type BundleNode {
  children: [BundleChildrenItem]
}

union BundleChildrenItem = BundleNode
````

`output`:
````
✔ Published initial schema.
````

Weird behavior during error reporting saying that I have many error (including missing Query type) when I have only one (missing type declaration for `Product`, I have to publish Product schema first indeed).

**Comment by dotansimha** [comment] 2022-12-27 17:06
Yeah, this is kinda weird. I will try to reproduce that in an integration test (right after figuring out what's flaky in https://github.com/kamilkisiela/graphql-hive/pull/883 😆😆😆 ) and will try to find the cause. Thank you for reporting it and sharing all the details, @Huljo !

**Comment by dotansimha** [comment] 2023-02-22 11:21
@Huljo it seems like the latest fixes and the new schema publishing flow has fixed that issue (https://the-guild.dev/blog/graphql-hive-improvements-in-schema-registry). 
Closing for now, please let me know if this needs to be reopened.

**Closed by dotansimha** 2023-02-22 11:21 UTC

**Comment by kdawgwilk** [comment] 2023-06-15 17:22
I am seeing a very similar issue I have 2 subgraphs `core-api` and `billify`

`core-api`

```gql
type Workspace @key(fields: "id") {
  id: ID!
  createdAt: DateTime!
  ...
}
```

`billify`

```gql
type Subscription @key(fields: "id") {
  id: ID!

  ...fields
}

extend type Workspace @key(fields: "id") {
  id: ID! @external
  subscription: Subscription
}
```

when I try and publish the `billify` schema I get these weird unrelated issues

```
✖ Detected 3 errors

   - Unknown type Subscription. Did you mean SubscriptionAddOn?
   - Type Mutation must define one or more fields.
   - Type Query must define one or more fields.

✖ Failed to publish schema
```

but when I remove the `extend type Workspace @key(fields: "id") {` def from `billify` it publishes just fine 🤷
