### ISSUE TITLE
schema:check failure; approval button

### ISSUE THREAD

**Issue by kmcgill88** [kamilkisiela/graphql-hive#3216] opened 2023-10-30 13:36 UTC
<img width="286" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/1992370/656aad4e-c3d2-49a0-9627-f46c019d87a2">

From what I can conclude this approval button only works with Github Actions? My team doesn't use Github and my expected behavior is similar to what Apollo does. The first check fails for a breaking change. If you'd like to proceed with the change anyway then click approve. Rerun the check and ✅ then the subsequent check allows the breaking change.

The docs were not clear to me what the approval button is and how it can be used.

**Comment by n1ru4l** [comment] 2023-10-30 14:08
Hey @kmcgill88, thank you for reporting your confusion. We are not 100% aware of how the approval of breaking changes works in Apollo.

In terms of how Hive works, you approve a schema check, not the single breaking changes within the schema check.
Thus, for subsequent schema checks, we do not know whether the breaking changes within it have been accepted before.

Accepting the individual (or all) breaking changes within a schema check and having that information available for the next schema check (that might run on a different git repository and/or branch) raises a lot of new questions for me.

Are the breaking changes within Apollo Studio globally (for all subgraphs, git repositories, branches, and commits) or only for the lifecycle of the development within a single git branch in a single git repository?

If the former is the case I feel like this would be slightly prone to false/missed breaking changes in case a field is re-introduced and removed in the future.

We want to improve the overall experience of this feature and are happy to hear your thoughts on this!

**Comment by larnacoeur** [comment] 2023-10-31 11:22
Hey @n1ru4,
I'm also a little bit confused on how approvals work right now in Hive.

We have a simple CI/CD flow in Azure (that follows the rules from Hive docs):
1. For Pull Requests we are executing schema:check using Hive CLI
2. For master (after PR approval process) we're publishing the schema

That works perfectly fine if there are no breaking changes to the schema.

In a scenario when Hive detects breaking change to the schema it obviously fails (with 1 code from CLI) and fails our PR pipeline (which is perfect), but when we go and approve this check in Hive app and rerun our PR pipeline, it fails again as it's treated as entirely new check which is not approved. I think the expected behaviour would be that if the check is performed from the same commit as previous, approved one, retrying schema:check shouldn't fail.

Am I missing something here or is it a bug?

**Comment by n1ru4l** [comment] 2023-10-31 11:39
Right now, the feature was developed in a way where the main use-case is GitHub actions.

The happy path for GitHub is the following (which of course is not optimal as this issue shows):

1. You develop your feature and the schema checks fail (which blocks merging on GitHub as the hive status check is required to pass)
2. You click the Approve button before merging, this will update the failed GitHub status check that is associated with the commit on GitHub
3. You can now click the merge button on the GitHub UI

There are two problems with it that we realized from this issue:

1. You expect the individual (or all) breaking changes within a schema check and having that information available/memorized for the next schema check that is running on the same git branch. This is tricky to solve without storing breaking change approvals "globally" (and not per git branch).
2. The implementation is developed for GitHub (Actions) "first", other CI systems cannot really benefit from the approval functionality. What @larnacoeur mentioned in https://github.com/kamilkisiela/graphql-hive/issues/3216#issuecomment-1787021128 could be a possible solution that we need to think about.

**Comment by kmcgill88** [comment] 2023-10-31 16:54
My use case, and expectation, match @larnacoeur exactly.

I'm also surprised that `schema:publish` does not do a `check` prior to publishing. I had to learn this the hard way.  I find `schema:check` nice for a PR but when the pipeline runs for a target I expected publish to only publish if it's safe to do so. Easy work around is always run check prior to publish. I'm curious what others expected here.

**Comment by comp615** [comment] 2023-11-02 15:11
> I'm also surprised that `schema:publish` does not do a `check` prior to publishing. I had to learn this the hard way. I find `schema:check` nice for a PR but when the pipeline runs for a target I expected publish to only publish if it's safe to do so. Easy work around is always run check prior to publish. I'm curious what others expected here.

Either way is fine. Not running a check on publish matches Apollo which I assume was the intent here. It's trivial either way to run a check then publish, or to put --no-check on the command. I think as-is makes the most sense as it's designed for the CI case where you'd usually put publish in the post-merge or deploy hooks and check in the PR hooks

**Comment by n1ru4l** [comment] 2023-11-03 16:21
Okay given the feedback from this issue, we came to the following conclusion and plan:

We want to change the Approval functionality to "allowing" the breaking changes for the single schema check for all subsequent schema checks on the same pull request/branch.

On GitHub Actions, we will simply get the pull request/branch via the environment variables (when using `hive schema:check --github`). Once it is implemented, the only change required will be to upgrade the Hive CLI version.

However, for other environments as mentioned in https://github.com/kamilkisiela/graphql-hive/issues/3216#issuecomment-1787021128, it will be necessary to manually provide a context (pull request id or branch name) that is unique for the lifecycle of a pull request/branch via a parameter. E.g. `hive schema:check --context "pr_12"`.

Then a schema check that shares the same "context" identifier will only fail if it contains breaking changes that have not yet been accepted for the given context identifier.

**Comment by n1ru4l** [comment] 2023-11-03 16:23
> @kmcgill88 https://github.com/kamilkisiela/graphql-hive/issues/3216#issuecomment-1787610892)
> 
> I'm also surprised that `schema:publish` does not do a `check` prior to publishing. [...]

This comment already contains the answer I would have written. https://github.com/kamilkisiela/graphql-hive/issues/3216#issuecomment-1790926654

**Comment by n1ru4l** [comment] 2023-11-06 08:18
Duplicate of https://github.com/kamilkisiela/graphql-hive/issues/2698

**Closed by n1ru4l** 2023-11-06 08:18 UTC
Labels: enhancement

**Comment by n1ru4l** [comment] 2023-11-16 13:41
Hey everyone, we just shipped https://github.com/kamilkisiela/graphql-hive/pull/3359 to production.

You can learn more in our product update: [Breaking change approval improvements](https://the-guild.dev/graphql/hive/product-updates/2023-11-16-schema-check-breaking-change-approval-context)
