### ISSUE TITLE
Insights: date range picker

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#3977] opened 2024-02-15 11:02 UTC
Use https://ui.shadcn.com/docs/components/date-picker

**Comment by n1ru4l** [comment] 2024-02-15 11:22
duplicate of https://github.com/kamilkisiela/graphql-hive/issues/3836

**Closed by n1ru4l** 2024-02-15 11:22 UTC

**Comment by kamilkisiela** [comment] 2024-02-15 11:28
lol it was hard to find :D
