### ISSUE TITLE
Bug?: Getting 403 for real s3 connection. Minio works just fine

### ISSUE THREAD

**Issue by klys-equinix** [kamilkisiela/graphql-hive#3461] opened 2023-11-27 12:26 UTC
Hi, I am trying to self host hive. I am not able to connect to the real S3 instance, I just keep getting 403s.
I have checked that the credentials i use work with nodejs S3 SDK, and I am unable to debug any further.
Could we at least have more logging here:
https://github.com/kamilkisiela/graphql-hive/blob/0861a6001851c9b3f2059ca13499ab26e286a6e2/packages/services/api/src/modules/cdn/providers/cdn.provider.ts#L109
To be able to tell what exactly went wrong with a S3 request?

**Comment by n1ru4l** [comment] 2023-11-27 13:25
@klys-equinix What additional logic could we log? We already log the request raw body https://github.com/kamilkisiela/graphql-hive/blob/0861a6001851c9b3f2059ca13499ab26e286a6e2/packages/services/api/src/modules/cdn/providers/cdn.provider.ts#L116

**Comment by klys-equinix** [comment] 2023-11-27 13:33
you are logging the response - and seemingly it is empty - as often for 403s:
```
2023-11-27 13:22:54 {"level":20,"time":1701087774362,"pid":1,"hostname":"9b30c9b4f4e2","msg":"Failed creating CDN access token. Head request on S3 returned unexpected status while checking token availability. (organizationId=c2c9fc1d-f8bf-4590-91e6-52d8897837c3, projectId=a4fabe69-5531-4e6e-9412-77299a51448b, targetId=4a11722b-22b8-481c-909a-e64712a36326, status=403) - (requestId=5ahZaZjcQFmMsheTB7oAmw/0000000000)"}
2023-11-27 13:22:54 {"level":20,"time":1701087774363,"pid":1,"hostname":"9b30c9b4f4e2","msg":" - (requestId=5ahZaZjcQFmMsheTB7oAmw/0000000000)"}
```
But you are not logging the request. Having sanitized request data would be very helpful. Also, are you running Hive successfully with actual S3 (not minio) ?

**Comment by klys-equinix** [comment] 2023-11-27 13:43
I can't build the app locally. Also, do you have any information if this was checked with actual S3? I can see that you are using a custom client instead of amazon SDK - https://github.com/kamilkisiela/graphql-hive/blob/main/packages/services/cdn-worker/src/aws.ts

**Comment by bczerwinski-equinix** [comment] 2023-11-27 13:49
We have tried different variants of `S3_ENDPOINT`, like:
- s3.REGION.amazonaws.com
- BUCKET.s3.REGION.amazonaws.com

for valid S3 credentials. However all of them result in 403 response from AWS

**Comment by n1ru4l** [comment] 2023-11-27 13:49
@klys-equinix No we never tested it with AWS S3. We use a custom client that works on both Cloudflare Worker and Node.js environments ([based on WinterCG](https://wintercg.org/). The Amazon SDK does not work on Worker Environments and, thus, is not a viable solution for us.

**Comment by klys-equinix** [comment] 2023-11-27 13:58
Ok, we will try to debug further if this is an issue with that custom client or if we are doing smth wrong

**Comment by n1ru4l** [comment] 2023-11-27 13:58
@klys-equinix @bczerwinski-equinix A potential solution to debug this without having to build the application locally can be to extract the client code ([`packages/services/cdn-worker/src/aws.ts`](https://github.com/kamilkisiela/graphql-hive/blob/55b0b30f409a4cfcd7d62954ce2d1d425e0b17f9/packages/services/cdn-worker/src/aws.ts#L1), and then try to invoke it as in application code.

**Comment by n1ru4l** [comment] 2023-11-27 14:01
@klys-equinix We have instructions for building locally in https://github.com/kamilkisiela/graphql-hive/blob/main/docs/DEVELOPMENT.md

**Comment by dotansimha** [comment] 2023-11-27 14:12
@klys-equinix Just to verify you have access, can you please try to run

```
$ aws configure
AWS Access Key ID: SAME_AS_YOU_USED_FOR_HIVE
AWS Secret Access Key: SAME_AS_YOU_USED_FOR_HIVE
Default region name: SAME_AS_YOU_USED_FOR_HIVE 
```

Then run `aws s3 ls` -> to verify you see the bucket you are using for Hive. 

Also, you can try to run `aws s3 ls s3://BUCKET_NAME` to see if you are able to list the files and access the actual bucket data (empty response is valid if this is a new bucket).

**Comment by klys-equinix** [comment] 2023-11-27 14:29
@dotansimha aws ls works just fine. I also checked that AWS nodejs SDK works fine too

**Comment by bczerwinski-equinix** [comment] 2023-11-27 14:38
@n1ru4l @dotansimha Did you consider using AWS SDK in your project? Comparing requests to S3 API generated by `hive-server` and those coming from `@aws-sdk` I think that it might be the simplest way to go

**Comment by bczerwinski-equinix** [comment] 2023-11-27 14:58
> Let's see if the docker images built from #3463 (tag: `f60469edfadc153706080ab5b437f53abef45f51`) will fix this issue.

We have faced S3 issues when tried to create CDN Access Token and I see that the fix also includes https://github.com/kamilkisiela/graphql-hive/blob/main/packages/services/api/src/modules/cdn/providers/cdn.provider.ts so fingers crossed!

**Comment by n1ru4l** [comment] 2023-11-27 14:58
@bczerwinski-equinix Can you please check whether the issue is resolved with the docker images from https://github.com/kamilkisiela/graphql-hive/pull/3463#issuecomment-1827993551?

As for the `S3_ENDPOINT` format, please use the format `https://s3.{region}.amazonaws.com](https://s3.us-east-1.amazonaws.com`

**Comment by bczerwinski-equinix** [comment] 2023-11-27 15:31
> @bczerwinski-equinix Can you please check whether the issue is resolved with the docker images from [#3463 (comment)](https://github.com/kamilkisiela/graphql-hive/pull/3463#issuecomment-1827993551)?
> 
> As for the `S3_ENDPOINT` format, please use the format `https://s3.{region}.amazonaws.com`

Now AWS request is being constructed in a different way:
- lacks `Authorization` header
- instead of headers path params are generated, with some new ones comparing to headers

Request response in 403.

Sample request:
```HEAD https://s3.{region}.amazonaws.com/{S3_BUCKET_NAME}/cdn-keys/ed64d23d-...-c646a8911436/5a28971b-...-2fe95bac4cff?X-Amz-Date=20231127T151531Z&X-Amz-Expires=86400&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential={S3_ACCESS_KEY_ID}%2F20231127%2F{region}%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=305be...95a```

**Comment by klys-equinix** [comment] 2023-11-28 08:44
> Let's see if the docker images built from #3463 (tag: `f60469edfadc153706080ab5b437f53abef45f51`) will fix this issue.

Version from this tag works fine for me

**Comment by n1ru4l** [comment] 2023-11-28 10:24
@klys-equinix Thank you for reporting, debugging, and verifying the fix of this issue. 🎉

In addition to the fix I also pushed some documentation updates for self-hosting to https://github.com/kamilkisiela/graphql-hive/pull/3463 which explains what endpoint and configuration to use for different S3 Compatible Object Storage providers.

As a follow-up task, I created https://github.com/kamilkisiela/graphql-hive/issues/3464

**Closed** 2023-11-28 10:40 UTC
Labels: bug
