### ISSUE TITLE
persist schema check filter state in url parameters

### ISSUE THREAD

**Issue by n1ru4l** [kamilkisiela/graphql-hive#3261] opened 2023-11-03 12:34 UTC
Right now, when you change a schema filter and then refresh the page the filter state is reset. Instead we should persist the state in the URL.

<img width="415" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/14338007/8ef22f7c-e7c9-40a7-a1f3-761cf2e671e2">

```
https://app.graphql-hive.com/the-guild/graph-ql-hive/staging/checks?filter_changes=1
https://app.graphql-hive.com/the-guild/graph-ql-hive/staging/checks?filter_changes=1&filter_errors=1
```

**Comment by deep-maheshwari** [comment] 2023-11-04 06:02
Hi @n1ru4l , I wanted to check if there are steps to reproduce in local development setup, if so can you please attach them here, I will be happy to take a look and raise a PR for this issue.

**Comment by n1ru4l** [comment] 2023-11-04 14:13
@deep-maheshwari You can follow this document for setting up your local dev environment: https://github.com/kamilkisiela/graphql-hive/blob/main/docs/DEVELOPMENT.md You can follow this guide for populating schema checks: https://the-guild.dev/graphql/hive/docs/get-started/single-project#schema-checks

**Comment by deep-maheshwari** [comment] 2023-11-04 15:20
> @deep-maheshwari You can follow this document for setting up your local dev environment: https://github.com/kamilkisiela/graphql-hive/blob/main/docs/DEVELOPMENT.md You can follow this guide for populating schema checks: https://the-guild.dev/graphql/hive/docs/get-started/single-project#schema-checks

Thanks, @n1ru4l for the info, but I have already setup the hive and know how to publish schemas, I just needed help with reproducing the issue that is stated. To be more precise, where do I set the schema filter and what URL are we talking about here?

**Comment by deep-maheshwari** [comment] 2023-11-04 17:53
@n1ru4l, After taking a look through the code and documentation I seem to have figured out what the problem is. Just to confirm on expected behavior, is it the case that when we toggle the switch in the checks page the state is consistent with what's there in the database? due to this when we refresh the page, the checks turned on is not showing up.

<img width="435" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/54976309/70c239c3-1f17-40fc-b284-2721c31ecc9d">

**Comment by deep-maheshwari** [comment] 2023-11-04 18:07
The problem lies in the declaration of the filter state to empty on [L#784](https://github.com/kamilkisiela/graphql-hive/blob/main/packages/web/app/pages/%5BorganizationId%5D/%5BprojectId%5D/%5BtargetId%5D/checks.tsx#L784), we need to either query the filter state from backend or if it's already present, use it to initialize state.

**Comment by deep-maheshwari** [comment] 2023-11-08 07:00
Hi @n1ru4l, a little bit of help in understanding flow would help me resolve this issue, can you please guide me on how can I check if the filter values are persisted in the database through the backend or not, If so how can I retrieve them? Right now it seems to be used everywhere just as a parameter but it's value never seems to be stored in DB.

**Comment by n1ru4l** [comment] 2023-11-09 09:43
It should be persisted in the URL as query parameters not in the database.

```
https://app.graphql-hive.com/the-guild/graph-ql-hive/staging/checks?filter_changes=1
https://app.graphql-hive.com/the-guild/graph-ql-hive/staging/checks?filter_changes=1&filter_errors=1
```

**Comment by deep-maheshwari** [comment] 2023-11-10 18:08
Hi @n1ru4l, thanks for clarification, I have raised PR - https://github.com/kamilkisiela/graphql-hive/pull/3366 based on the inputs, please assign this issue to me. 
Also I don't find an option to add reviewers to the PR, how can I do so?

**Closed** 2023-11-20 10:09 UTC
Labels: enhancement, help wanted, good first issue
