### ISSUE TITLE
GraphQL Hive CLI - allow to purge/delete service from a registry

### ISSUE THREAD

**Issue by cookieMr** [kamilkisiela/graphql-hive#817] opened 2022-12-15 13:54 UTC
Allow users to delete/purge schema registry of current schema. Such functionality might be useful when removing/retiring a sub-graph from a service and removing its related schema would be better than forcing it to be empty.

```bash
hive schema:purge --token SUPER-SECRET --iKnowWhatIAmDoing --service The2ndService
```

I can do checks, i can do publish, but i cannot get rid off of old schema. This would be particularly helpful for test environments where we do push a lot. Sometimes i would like to check reconfiguration of registry.

```bash
hive schema:check "schema.graphql" --token SUPER-SECRET --service The2ndService
hive schema:publish "schema.graphql" --token SUPER-SECRET --service The2ndService
```

**Comment by kamilkisiela** [comment] 2022-12-15 13:56
#279

**Comment by cookieMr** [comment] 2022-12-15 14:04
I think you can close this issue (to keep your backlog clean) in favor of the one you just provided (and put some pressure on it :smiling_face_with_tear: ).

**Comment by n1ru4l** [comment] 2022-12-16 10:21
Duplicate of https://github.com/kamilkisiela/graphql-hive/issues/279

**Closed by n1ru4l** 2022-12-16 10:21 UTC

**Comment by kamilkisiela** [comment] 2023-02-07 16:19
https://github.com/kamilkisiela/graphql-hive/blob/main/packages/libraries/cli/README.md#hive-schemadelete-service

**Comment by cookieMr** [comment] 2023-02-07 16:33
Thx Kamil!
