### ISSUE TITLE
self-hosted federation supergraph CDN fetch 404

### ISSUE THREAD

**Issue by gadamsfd** [kamilkisiela/graphql-hive#2714] opened 2023-08-08 05:13 UTC
I'm following the directions here: https://the-guild.dev/graphql/hive/docs/get-started/apollo-federation#fetch-your-supergraph in combination with https://the-guild.dev/graphql/hive/docs/self-hosting/get-started. I've created a CDN access token in my project target, and using curl I get a 404. My project is a federation project, and I'm using the CDN url displayed with the Apollo Federation dropdown option selected: http://localhost:8082/artifacts/v1/47396693-70f6-4fb8-9427-e7af1643049e/supergraph

```
➜  hive curl -v -L -H "X-Hive-CDN-Key: hv2NGZjMTY1OGQtZWY5Zi00ZWM2LThjOWEtNzQ0ZTNmZDk5Mzg1OmE0M2Y1NjEyZjY2ZGFjNmUxNGQwMTc0YWZiZTU1NzYwYmYyZDYwMmY=" http://localhost:8082/artifacts/v1/47396693-70f6-4fb8-9427-e7af1643049e/supergraph
*   Trying 127.0.0.1:8082...
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET /artifacts/v1/47396693-70f6-4fb8-9427-e7af1643049e/supergraph HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.88.1
> Accept: */*
> X-Hive-CDN-Key: hv2NGZjMTY1OGQtZWY5Zi00ZWM2LThjOWEtNzQ0ZTNmZDk5Mzg1OmE0M2Y1NjEyZjY2ZGFjNmUxNGQwMTc0YWZiZTU1NzYwYmYyZDYwMmY=
>
< HTTP/1.1 404 Not Found
< vary: Origin
< access-control-allow-origin: *
< content-type: text/plain;charset=UTF-8
< content-length: 10
< Date: Tue, 08 Aug 2023 05:10:36 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
Not found.%
```

in the docker-compose logs, this is all I see:
```
hive-server-1                | {"level":30,"time":1691471470056,"pid":1,"hostname":"eb6affb4318c","msg":"[404] (::ffff:10.89.0.181) GET /artifacts/v1/47396693-70f6-4fb8-9427-e7af1643049e/supergraph"}
```

```

**Comment by gadamsfd** [comment] 2023-08-08 05:18
this is with graphql-hive/server docker image with digest sha256:d8d3cfa4b49e26dba2357faf849d5d02c62f22c045f1b42c35bdf1b9a59be144

**Comment by n1ru4l** [comment] 2023-08-08 07:23
@gadamsfd Did you set the correct environment variables on the `server` docker container for exposing the CDN route handlers? https://github.com/kamilkisiela/graphql-hive/blob/48eba65e511167cec136f9b4d43622aaf615338c/packages/services/server/README.md#L38-L39

**Comment by gadamsfd** [comment] 2023-08-08 14:38
I tried deleting the project, republishing the schema, generating a new CDN access token, and hitting the supergraph endpoint again via curl, no luck, still 404.

**Comment by gadamsfd** [comment] 2023-08-08 14:50
I also tried removing the docker volumes `docker-compose -f docker-compose.with-env.yml down -v` and starting over, still 404.

**Comment by gadamsfd** [comment] 2023-08-08 15:03
docker-compose down -v would have destroyed all containers. To be extra sure, I just ran `docker inspect hive-server-1`, here's the environment section:
```
"Env": [
                    "AUTH_ORGANIZATION_OIDC=1",
                    "CDN_API_BASE_URL=http://localhost:8082",
                    "S3_BUCKET_NAME=artifacts",
                    "YARN_VERSION=1.22.19",
                    "PORT=3001",
                    "TOKENS_ENDPOINT=http://tokens:3003",
                    "CLICKHOUSE_USERNAME=clickhouse",
                    "SUPERTOKENS_CONNECTION_URI=http://supertokens:3567",
                    "CLICKHOUSE_HOST=clickhouse",
                    "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                    "ENVIRONMENT=production",
                    "POSTGRES_PASSWORD=f2d8e574b17bbe3a77ea0f56ba876757",
                    "container=podman",
                    "WEBHOOKS_ENDPOINT=http://webhooks:3005",
                    "NODE_ENV=production",
                    "S3_PUBLIC_URL=http://localhost:8083",
                    "CLICKHOUSE_PASSWORD=4a76f3ee0b2d6b618f884e8913f868d1",
                    "REDIS_HOST=redis",
                    "S3_ACCESS_KEY_ID=minioadmin",
                    "SCHEMA_ENDPOINT=http://schema:3002",
                    "REDIS_PORT=6379",
                    "CDN_API=1",
                    "WEB_APP_URL=http://localhost:8080",
                    "CDN_AUTH_PRIVATE_KEY=c7944ff5e01c300ff975e5223c1a9fb7",
                    "TERM=xterm",
                    "RELEASE=",
                    "NODE_VERSION=18.17.0",
                    "POSTGRES_PORT=5432",
                    "POSTGRES_USER=postgres",
                    "EMAILS_ENDPOINT=http://emails:3011",
                    "POSTGRES_DB=registry",
                    "CLICKHOUSE_PORT=8123",
                    "S3_SECRET_ACCESS_KEY=minioadmin",
                    "S3_ENDPOINT=http://s3:9000",
                    "CLICKHOUSE_PROTOCOL=http",
                    "REDIS_PASSWORD=914c7d25200cfd75ba224988abc09ce7",
                    "SUPERTOKENS_API_KEY=2195b65620a3d67f69e44ec41fee1713",
                    "POSTGRES_HOST=db",
                    "ENCRYPTION_SECRET=8563af699a509ff5925c8c1e330435b6",
                    "SCHEMA_POLICY_ENDPOINT=http://policy:3012",
                    "HOME=/root",
                    "HOSTNAME=0a596b6ce046"
               ],
```

**Comment by n1ru4l** [comment] 2023-08-08 15:09
@gadamsfd I just successfully followed the self-hosting instructions and everything is working as expected. Can you try using the latest images from the main branch?

**Comment by gadamsfd** [comment] 2023-08-08 16:21
I just did a docker-compose pull and docker-compose up and here's the image related output from docker inspect hive-server-1:
```
"Image": "9a510e8c6cdebdde1010b122f718542ea5f1a82443ef31a6881b73f45e58fae2",
          "ImageDigest": "sha256:77c1d8d94baa972709d9f88c949988cae3a19c5a3dcb03471792b046c1fcbab5",
          "ImageName": "ghcr.io/kamilkisiela/graphql-hive/server:latest"
```
this digest matches https://github.com/kamilkisiela/graphql-hive/pkgs/container/graphql-hive%2Fserver/116818623?tag=460897a5fb6962ddfdbd8c062fb5807bb525fa2a, which I think is the latest image published.

```
➜  hive curl -v -L -H "X-Hive-CDN-Key: hv2YTg3MmQ5YjAtYmYxZS00OWNlLWI4ZTktOGFhNDI3YzA4ZGRjOjYxNzMwMTYxNDAyZmFhM2IyYzViMGEwNDUxZTc0YTQ0M2VlZWI3Nzg=" http://localhost:8082/artifacts/v1/f109b98c-f92b-4623-848e-1fd1a2e6e8d8/supergraph
*   Trying 127.0.0.1:8082...
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET /artifacts/v1/f109b98c-f92b-4623-848e-1fd1a2e6e8d8/supergraph HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.88.1
> Accept: */*
> X-Hive-CDN-Key: hv2YTg3MmQ5YjAtYmYxZS00OWNlLWI4ZTktOGFhNDI3YzA4ZGRjOjYxNzMwMTYxNDAyZmFhM2IyYzViMGEwNDUxZTc0YTQ0M2VlZWI3Nzg=
>
< HTTP/1.1 404 Not Found
< vary: Origin
< access-control-allow-origin: *
< content-type: text/plain;charset=UTF-8
< content-length: 10
< Date: Tue, 08 Aug 2023 16:20:53 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
Not found.%
```

I'm on podman on an m1 mac. Could that have anything to do with it?

**Comment by n1ru4l** [comment] 2023-08-08 16:44
I am not using podman, so I can not verify it is an issue with that. Could you try a fresh instance with the docker-compose.yml file and confirm that it is still an issue? I can not reproduce the issue you are having as instructed in the self-hosting getting started guide.

**Comment by gadamsfd** [comment] 2023-08-08 16:48
I just ran through the self-hosting guide from the beginning after purging everything from docker (docker system prune -a), and ended up with the same 404. With podman I have to make a few modifications to docker-compose.community.yml, specifically, I have to use named volumes, otherwise I get file permissions errors. 

[docker-compose.community.yml.txt](https://github.com/kamilkisiela/graphql-hive/files/12293917/docker-compose.community.yml.txt)
[hive.env.txt](https://github.com/kamilkisiela/graphql-hive/files/12293878/hive.env.txt)

After getting hive running (using the instructions to embed the env into docker-compose.with-env.yml), I log in, create a project, and in the development target, create a registry access token and cdn access token, then publish my 5 subgraph schemas 
[publish.sh.txt](https://github.com/kamilkisiela/graphql-hive/files/12293908/publish.sh.txt)

then try to fetch the supergraph schema using curl
[fetch.sh.txt](https://github.com/kamilkisiela/graphql-hive/files/12293909/fetch.sh.txt)

I'm not missing any steps, am I?

**Comment by gadamsfd** [comment] 2023-08-08 17:06
I tried it again, with the product and reviews schemas from https://the-guild.dev/graphql/hive/docs/get-started/apollo-federation and I'm able to get a supergraph schema for that. It must have something to do with my subgraph schemas.

**Comment by gadamsfd** [comment] 2023-08-08 17:38
ok, I figured it out. We have some subgraph schemas that include
`extend type Subscription { ... }`
with this in place, the supergraph fetch gives 404. If I comment it out, it works. 
We're using graphql-go-tools, which supports federated subscriptions. Does hive not support that?

**Comment by n1ru4l** [comment] 2023-08-09 07:46
For supporting `Subscription` types within your federated GraphQL schema you will need to use external composition with Apollo Federation 2.

See [External Schema Composition](https://the-guild.dev/graphql/hive/docs/management/external-schema-composition) and [Self-Hosting: Apollo Federation 2](https://the-guild.dev/graphql/hive/docs/self-hosting/federation-2).

_______

Aside from that it seems like there is an inconsistency issue in case the supergraph generation fails. I will investigate this issue and make sure that the whole schema publishing process fails in case there is an issue with the supergraph.

**Comment by n1ru4l** [comment] 2023-08-09 08:32
So this is what happens when you publish a GraphQL schema that has a `Subscription` type with the built-in Federation 1 support.

```graphql
# examples/federation.products.graphql

type Product @key(fields: "id") {
  id: ID!
}

type Subscription {
  productCreated: Product
}

```

```bash
$ hive schema:publish --service posts --url http://localhost:1111/graphql examples/federation.products.graphql

✔ Schema published
```

<img width="1212" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/14338007/e58282c3-e6fe-45f3-a9a5-c8c0303f9ba1">

The schema publish succeeds, even though the schema composition fails. Because the schema composition fails, no supergraph and SDL is written to the CDN as the CDN always represents the latest VALID (composable) state of the subgraphs.

You can check, whether a schema publish would result in failed composition using the `hive schema:check` command.

```bash
$ hive schema:check --service posts examples/federation.products.graphql

✖ Detected 1 error

   - [posts] Subscription -> `Subscription` is an extension type, but `Subscription` is not defined in any service
```

After I updated the project to use external composition with Federation 2, the publish succeeds.

```graphql
# examples/federation.products.graphql

type Product @key(fields: "id") {
  id: ID!
}

type Subscription {
  productCreated: Product
  productUpdated: Product
}

```

```bash
hive schema:publish --service posts --url http://localhost:1111/graphql examples/federation.products.graphql

ℹ Detected 1 change

   - Field productUpdated was added to object type Subscription
```

<img width="618" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/14338007/b2fba78b-4920-43ba-9e28-5a5e419cded1">


<img width="997" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/14338007/7db6dc2e-5038-45a2-8169-9a63e4ef38aa">

**Comment by n1ru4l** [comment] 2023-08-09 08:36
I will close this issue, feel free to re-open it if you still experience any issues after moving to the external composition with Apollo Federation 2.

**Closed by n1ru4l** 2023-08-09 08:36 UTC
Labels: question

**Comment by kamilkisiela** [comment] 2023-08-09 19:27
We allow to publish schema with composition errors but our system does not push Supergraph SDL and other artifacts to the CDN. The reason for it is that sometimes you want to introduce a new subgraph that breaks the composition or simply migrate things from one subgraph to another. Same applies to a supergraph being built from scratch. Let's say you have 6 subgraphs and you want to publish them to GraphQL Hive. If we would reject composition errors, you would have to publish them in correct order or with modifications in subgraphs.
