### ISSUE TITLE
Add Requests Over Time chart (current and previous month) to Subscription page

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#4143] opened 2024-03-04 08:37 UTC
Page: `[org]/view/subscription`
Show it only for Pro and Enterprise plans as Hobby stores data for only 7 days.

Bonus points: allow to compare against previous months.

**Comment by n1ru4l** [comment] 2024-03-04 08:38
duplicate of https://github.com/kamilkisiela/graphql-hive/issues/3929

**Closed** 2024-03-21 10:00 UTC
