### ISSUE TITLE
 Cannot query field "warnings" on type "SchemaCheckSuccess"

### ISSUE THREAD

**Issue by pierrebiver** [kamilkisiela/graphql-hive#2310] opened 2023-05-24 12:50 UTC
Hello, 
When trying to use the Hive CLI and check my schema I'm getting the following error:
` Error: Cannot query field "warnings" on type "SchemaCheckSuccess".`
I'm using hive CLI 0.22.0 and a self hosted version of Hive with the following Docker tag: `:0a6c868f8898050a0855078be6bd94a57ae6055a`

**Comment by n1ru4l** [comment] 2023-05-24 12:59
Duplicate of https://github.com/kamilkisiela/graphql-hive/issues/2269

**Closed by n1ru4l** 2023-05-24 12:59 UTC

**Comment by pierrebiver** [comment] 2023-05-24 13:22
Hello, this is a duplicate but it was not solved. I updated my Hive this morning and got the error later during the day so the bug is still there.

**Comment by n1ru4l** [comment] 2023-05-24 13:27
Please double-check check you are running the correct docker image versions. If you just updated the docker-compose file and run `docker compose up` it is very likely that you are still running the old images. The `--force-recreate` flag can be used for recreating the containers.

See https://docs.docker.com/engine/reference/commandline/compose_up

**Comment by pierrebiver** [comment] 2023-05-24 13:51
ahh it worked, I was using `restart` and though it would update the container but it seems not. Thanks 🥳
