### ISSUE TITLE
kafka Docker container crashed

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [kamilkisiela/graphql-hive#370] opened 2022-09-15 15:08 UTC
After running `yarn setup`, when I checked containers I observed the Kafka related container crashed.

Getting the below error in the container logs:

```
===> User
uid=1000(appuser) gid=1000(appuser) groups=1000(appuser)
===> Configuring ...
===> Running preflight checks ... 
===> Check if /var/lib/kafka/data is writable ...
Command [/usr/local/bin/dub path /var/lib/kafka/data writable] FAILED !
```

It seems there is an issue with Kafka, you can go through [issue similar to this](https://github.com/confluentinc/kafka-images/issues/131).

**Comment by kamilkisiela** [comment] 2022-09-19 07:42
@DilLip-Chowdary-Codes can you run different versions of Kafka and see which one works for you? I can't reproduce this issue.

**Comment by DilLip-Chowdary-Codes** [comment] 2022-09-22 09:15
@kamilkisiela I'm trying to setup this in AWS EC2, after running `yarn setup`, when I check the status of the container `docker ps -a`

I got the above error.

Yeah, I am trying out different versions.

**Comment by DilLip-Chowdary-Codes** [comment] 2022-09-22 10:33
@kamilkisiela 

##### Additional Info

**OS**: Ubuntu 20.04.5 LTS (AWS EC2)
**Docker Version**: 20.10.18, build b40c2f6
**Docker Compose Version**: v2.11.1

and if it's working for you, can you send the docker images with a tag and also the docker & docker-compose that's your server using currently?

The below docker images used in `yarn setup` process failed to create a container.

- `confluentinc/cp-kafka:7.1.1-1-ubi8.amd64`
- `confluentinc/cp-zookeeper:7.1.1-1-ubi8.amd64`
- `bitnami/redis:6.2`

**Comment by kamilkisiela** [comment] 2022-10-18 09:13
@DilLip-Chowdary-Codes can you try #502?

**Comment by dotansimha** [comment] 2022-12-12 18:00
@kamilkisiela and @n1ru4l recently did some updated to the images, @DilLip-Chowdary-Codes can you please check with the latest Compose file?

**Comment by dotansimha** [comment] 2023-01-02 07:59
@DilLip-Chowdary-Codes I'm closing for now. Please let me know if the issue persists with the latest version, and I'll reopen if needed.

**Closed by dotansimha** 2023-01-02 07:59 UTC
